In [14]:
!pip install pyspan
import pandas as pd
import pyspan as ps

Requirement already satisfied: pyspan in /usr/local/lib/python3.10/dist-packages (0.2.7)
Requirement already satisfied: numpy<2.0.0 in /usr/local/lib/python3.10/dist-packages (from pyspan) (1.26.4)
Requirement already satisfied: pandas<=2.2.2 in /usr/local/lib/python3.10/dist-packages (from pyspan) (2.2.2)
Requirement already satisfied: pyspellchecker==0.8.1 in /usr/local/lib/python3.10/dist-packages (from pyspan) (0.8.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<=2.2.2->pyspan) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<=2.2.2->pyspan) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<=2.2.2->pyspan) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<=2.2.2->pyspan) (1.16.0)

In [23]:
pd.set_option('display.max_columns' , None)
df = pd.read_csv("/content/Diwali-Sale-Data.csv", encoding="ISO-8859-1")

df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status,unnamed1
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN,NaN

In [ ]:
# remove unnecessary column
# inspect and handle null value

In [24]:
# remove unnamed1 column fron table
df  =  ps.remove(df , operation = 'columns' , columns = 'unnamed1')
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,NaN
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,NaN
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,NaN
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,NaN
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,NaN

In [25]:
# handle null values
#  to display all rows if rows show ...
pd.set_option('display.max_rows' , None)

df.isnull().sum()

User_ID                 0
Cust_name               0
Product_ID              0
Gender                  0
Age Group               0
Age                     0
Marital_Status          0
State                   0
Zone                    0
Occupation              0
Product_Category        0
Orders                  0
Amount                 12
Status              11251
dtype: int64

In [26]:
# replace null value "Null Values"

df =  ps.handle_nulls(df , columns = 'Status' , action = 'replace' , with_val = 'Null Values')

In [27]:
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,Null Values
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,Null Values
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,Null Values
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,Null Values
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,Null Values

In [30]:
# count category
df['Product_Category'].value_counts()

Product_Category
Clothing & Apparel       2655
Food                     2493
Electronics & Gadgets    2087
Footwear & Shoes         1064
Household items           520
Beauty                    422
Games & Toys              386
Sports Products           356
Furniture                 353
Pet Care                  212
Office                    113
Stationery                112
Books                     103
Auto                      100
Decor                      96
Veterinary                 81
Tupperware                 72
Hand & Power Tools         26
Name: count, dtype: int64

In [32]:
# value_count for age
df['Age'].value_counts()

Age
30    522
26    494
28    460
29    454
31    448
32    444
35    443
34    439
27    432
33    429
20    252
22    247
45    247
21    245
44    245
19    242
38    237
23    233
39    231
41    230
25    229
43    227
40    221
24    221
36    218
50    217
37    214
47    210
18    210
42    194
46    189
48    188
49    183
54    176
52    171
53    169
51    159
55    157
16     61
15     53
13     53
12     51
17     46
14     32
64     21
76     20
87     17
61     16
69     16
63     15
75     15
89     15
85     14
58     13
66     13
86     12
65     12
68     12
84     12
56     12
83     12
71     11
90     11
67     11
88     11
79     11
73     10
57     10
60     10
74     10
78      9
91      9
77      9
72      9
82      8
80      8
81      8
70      7
92      7
59      7
62      5
Name: count, dtype: int64

In [34]:
# interquartile range (iqr)
df = ps.detect_outliers(df, method='iqr', threshold=1.5 , columns = 'Age')

Total number of outliers detected across columns: 283
Original data shape: (11251, 14)
Data shape after removing outliers: (10968, 14)

In [36]:
df.shape

(10968, 14)

In [37]:
df.head()

,User_ID,Cust_name,Product_ID,Gender,Age Group,Age,Marital_Status,State,Zone,Occupation,Product_Category,Orders,Amount,Status
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,Null Values
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,Null Values
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,Null Values
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,Null Values
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,Null Values

In [40]:
cleaned_df = ps.auto_rename_columns(df)

All column names are already clean and readable!

In [42]:
df.head()

,User Id,Just Name,Product Id,Gender,Age Group,Age,Marital Status,State,Zone,Occupation,Product Category,Orders,Amount,Status
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,Null Values
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,Null Values
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,Null Values
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,Null Values
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,Null Values

In [43]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

MessageError: Error: credential propagation was unsuccessful

In [44]:
ps.display_logs()

Function "remove" was called at line 2 with parameters: df=<DataFrame: 8734 rows x 24 columns>, operation=columns, columns=about.
Function "remove" was called at line 2 with parameters: df=<DataFrame: 8734 rows x 24 columns>, operation=columns, columns=negotiating and closing major deals to form mutually beneficial relationships - my can-do attitude is my biggest strength and motivator.I have a strong commitment to deliver high quality products and services with full integrity.
Function "remove" was called at line 1 with parameters: df=<DataFrame: 11251 rows x 15 columns>, operation=columns, columns=unnamed1.
Function "remove" was called at line 2 with parameters: df=<DataFrame: 11251 rows x 15 columns>, operation=columns, columns=unnamed1.
Function "handle_nulls" was called at line 3 with parameters: df=<DataFrame: 11251 rows x 14 columns>, columns=Status, action=replace, with_val=Null Values.
Function "detect_outliers" was called at line 2 with parameters: df=<DataFrame: 11251 rows x 14 columns>, method=iqr, threshold=1.5.
Function "detect_outliers" was called at line 2 with parameters: df=<DataFrame: 11251 rows x 14 columns>, method=iqr, threshold=1.5, columns=Age.
Function "auto_rename_columns" was called at line 1 with parameters: df=<DataFrame: 10968 rows x 14 columns>.

In [45]:
df.head()

,User Id,Just Name,Product Id,Gender,Age Group,Age,Marital Status,State,Zone,Occupation,Product Category,Orders,Amount,Status
0,1002903,Sanskriti,P00125942,F,26-35,28,0,Maharashtra,Western,Healthcare,Auto,1,23952.0,Null Values
1,1000732,Kartik,P00110942,F,26-35,35,1,Andhra Pradesh,Southern,Govt,Auto,3,23934.0,Null Values
2,1001990,Bindu,P00118542,F,26-35,35,1,Uttar Pradesh,Central,Automobile,Auto,3,23924.0,Null Values
3,1001425,Sudevi,P00237842,M,0-17,16,0,Karnataka,Southern,Construction,Auto,2,23912.0,Null Values
4,1000588,Joni,P00057942,M,26-35,28,1,Gujarat,Western,Food Processing,Auto,2,23877.0,Null Values